name: "Install RocksDB v10.5.1"
description: "Build and install RocksDB shared library with caching"

runs:
  using: composite
  steps:
    - name: Prepare directory
      shell: bash
      run: mkdir -p $HOME/.rocksdb
    - name: Cache RocksDB shared
      id: cache-rocksdb
      uses: actions/cache@v3
      with:
        path: ${{ env.HOME }}/.rocksdb
        key: rocksdb-v10.5.1-${{ runner.os }}
        restore-keys: rocksdb-v10.5.1-

    - name: Install cached artifacts into /usr/local
      if: steps.cache-rocksdb.outputs.cache-hit == 'true'
      shell: bash
      run: |
        sudo rsync -a --delete $HOME/.rocksdb/ /usr/local/

    - name: Install RocksDB shared
      if: steps.cache-rocksdb.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgflags-dev \
            libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

        git clone --depth=1 --branch v10.5.1 https://github.com/facebook/rocksdb.git /tmp/rocksdb
        cd /tmp/rocksdb
        make shared_lib -j"$(nproc)" PORTABLE=1
        make install-shared PREFIX=$HOME/.rocksdb

    - name: Copy RocksDB into /usr/local
      shell: bash
      run: |
        sudo rsync -a --delete $HOME/.rocksdb/ /usr/local/

    - name: ldconfig
      shell: bash
      run: sudo ldconfig
